version: "3"
services:
  app:
    build: ./
    container_name: express
    depends_on:
      - postgres
    environment:
      DATABASE_CONNECTION_STRING: postgresql://user:pass@postgres:5432/db
      NODE_ENV: development
      PORT: 8080
    ports:
      - "80:8080"
    volumes:
      - .:/app/
    command:
      sh -c 'yarn && yarn start:dev'

  postgres:
    image: postgres:10.4
    container_name: db
    ports:
      - "5432:5432"
    volumes:
      - ./docker_data/db-docker:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: db