version: "3"
services:
  app:
    build: .
    container_name: express
    depends_on:
      - postgres
    environment:
      DATABASE_CONNECTION_STRING: postgres://user:pass@postgres:5432/db
      NODE_ENV: development
      PORT: 8080
    ports:
      - "8080:8080"
    command: yarn start
    volumes:
      - .:/app/

  postgres:
    image: postgres:10.4
    container_name: db
    ports:
      - "5432:5432"
    volumes:
      - ./db-data:/var/lib/postgresql
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: db